// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Nmc1Rj26e7jg8Ubsrtl4emsg0wjyx3s',
    appId: '1:256905096017:android:47e861467c9c19cce74170',
    messagingSenderId: '256905096017',
    projectId: 'chat-app-eb5df',
    databaseURL: 'https://chat-app-eb5df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-eb5df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4pQ64SMydUnjRy69OcvsPNiZ8JokukVk',
    appId: '1:256905096017:ios:677c8fa1a96884c4e74170',
    messagingSenderId: '256905096017',
    projectId: 'chat-app-eb5df',
    databaseURL: 'https://chat-app-eb5df-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chat-app-eb5df.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

}